### ISSUE TITLE
Regex for Spam Usernames

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/UserStalker#1]
One of the Puzzling Stack Exchange moderators, Rubio, has provided us with dataset of usernames which were used to spam Puzzling Stack Exchange. 

The list is here https://pastebin.com/CkeV99c5 

Can we come up with a new Regex list to catch **most** of these spammers? 

I need some help to _create the regex list_, not to develop anything. We can use a new file on GH to store the new regexes and just use the same code which we are using to match against the smokey blacklisted username list.

**Comment by rjrudman** [comment]
A regex-trie may be useful here. 

Here's an explanation
https://stackoverflow.com/questions/42742810/speed-up-millions-of-regex-replacements-in-python-3/42789508#42789508

**Comment by Bhargav-Rao** [comment]
Interesting, thanks for that.

**Comment by Bhargav-Rao** [comment]
If any one wants to contribute, drop in the regexes into this file here https://github.com/SOBotics/UserStalker/blob/master/data/blacklistRegex.txt

**Comment by rjrudman** [comment]
Are you happy with a computer generated regex-trie, or are you more after a human readable regex?

**Comment by Bhargav-Rao** [comment]
Anything is fine. As long as it does the job.

**Comment by adeak** [comment]
Note that my uneducated impression is that these are just vague guidelines to help figure out filters for the future. Catching all those Mayweather vs McGregor spam accounts won't be terribly helpful going forward. Similarly, filtering for `mlbopeningdayx` will probably be less useful. So my layman's impression is that throwing these names into a TRIE will not necessarily be the best course of action. But I'm curious of whatever we can do :)

**Comment by adeak** [comment]
Come to think of it, in cases of false positives one often wants to look at the pattern that was triggered. So if a TRIE is included, it would probably be prudent to additionally provide the list of keywords from which the TRIE was generated.

**Comment by rjrudman** [comment]
@adeak Yeah, you raise a good point if we're trying to catch future spammers

**Comment by Papershine** [comment]
There is a blacklisted username list by Charcoal for SmokeDetector [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/blacklisted_usernames.txt)

**Comment by Bhargav-Rao** [comment]
Yeah, [we're using that](https://github.com/SOBotics/UserStalker#what-data-are-we-using), but it certainly isn't as comprehensive as Rubio's list.

**Comment by codygray** [comment]
I'm marking this as "closed", because the action items have been completed.

We are now using all of the regex blacklists available from HeatDetector (to detect offensive words) as well as those available from Charcoal's SmokeDetector project (which will detect known trolls/spammers, as well as known problematic patterns). Plus, User Stalker has its own user-name blacklist built in, which includes Rubio's list, and is meant to be kept up-to-date by any moderator who handles the User Stalker reports.

Help is, of course, always welcome on improving and/or expanding the regexes in blacklists. If you have something you want to add or improve, simply submit a pull request (PR) for one of the existing patterns (https://github.com/SOBotics/UserStalker/tree/master/patterns). If you have a more complex suggestion, please open a new Issue.
